<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreRelationShipRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'related_to_id' => 'nullable',
            'relation_id' => "required"
        ];
    }

    public  function attributes()
    {
        return [
            'related_to_id' => 'Member',
            'telephone' => 'Telephone',
            'relation_id' => "Relation"
        ]; // TODO: Change the autogenerated stub
    }
}
