<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreHelpProvidedRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'help_cat_id' => 'required',
            'service_cost' => 'required',
            'help_type_id' => 'required',
            'authorized_by' => 'required',
            'authorized_date' => 'required',
            'payout_received_by' => 'required',
            'date_payout' => 'required',
            'images' => 'required|array',
        ];
    }
        public function attributes()
    {
        return [
            'help_cat_id' => 'Help Category',
            'help_type_id' => 'Help Type',
            'payout_received_by' => 'Name Of Help Recipient',
            'date_payout' => 'Date Received',
        ]; // TODO: Change the autogenerated stub
    }
}
